import { Seller, Buyer, Interest, QualityAssurance, Shipment, Notification } from './types';

export const INITIAL_SELLERS: Seller[] = [
    {
        sellerId: 'S001',
        companyName: 'PSPG Consultancy Pvt Ltd',
        contactPerson: 'Rahul Sharma',
        phone: '+919876543210',
        email: 'contact@pspg.in',
        country: 'India',
        region: 'Jaipur',
        productsOffered: ['Rice', 'Spices'],
        productDetails: 'Basmati rice, 1000 MT/month, GAP certified',
        pricePerUnit: 480,
        monthlyCapacity: 1000,
        availableQuantity: 500,
        qualityLevel: 'Premium',
        certifications: ['GAP', 'ISO'],
        qualityAssuranceProcess: '3-stage QC, lab testing',
        coldChainCapability: false,
        temperatureRange: 'Ambient',
        approvalStatus: 'Approved',
        approvedBy: 'Mohit',
        approvalDate: '2026-01-01',
        status: 'Active',
    },
    {
        sellerId: 'S002',
        companyName: 'Flowbotics Technologies Pvt Ltd',
        contactPerson: 'Amit Verma',
        phone: '+919988776655',
        email: 'amit@flowbotics.in',
        country: 'India',
        region: 'Gurgaon',
        productsOffered: ['Vegetables', 'Fresh Produce'],
        productDetails: 'Fresh seasonal vegetables, farm to fork',
        pricePerUnit: 350,
        monthlyCapacity: 500,
        availableQuantity: 300,
        qualityLevel: 'Premium',
        certifications: ['GLOBALGAP', 'ISO'],
        qualityAssuranceProcess: 'Residue checks, sorting',
        coldChainCapability: true,
        temperatureRange: '0-4°C',
        approvalStatus: 'Approved',
        approvedBy: 'Mohit',
        approvalDate: '2026-01-02',
        status: 'Active',
    },
    {
        sellerId: 'S003',
        companyName: 'Flowbotics International Trading FZCO',
        contactPerson: 'Sarah Jenkins',
        phone: '+971501234567',
        email: 'sarah@fbtradings.com',
        country: 'UAE',
        region: 'Dubai',
        productsOffered: ['Rice', 'Tea', 'Spices'],
        productDetails: 'Export quality tea and spices',
        pricePerUnit: 600,
        monthlyCapacity: 2000,
        availableQuantity: 1500,
        qualityLevel: 'Standard',
        certifications: ['APEDA', 'ISO'],
        qualityAssuranceProcess: 'Standard export checks',
        coldChainCapability: false,
        temperatureRange: 'Ambient',
        approvalStatus: 'Approved',
        approvedBy: 'Mohit',
        approvalDate: '2026-01-03',
        status: 'Active',
    }
];

export const INITIAL_BUYERS: Buyer[] = [
    {
        buyerId: 'B001',
        companyName: 'Unicorn Supply Singapore',
        contactPerson: 'John Lim',
        phone: '+6591234567',
        email: 'john@unicorn.sg',
        country: 'Singapore',
        city: 'Singapore',
        productInterest: 'Rice',
        quantityNeeded: 500,
        budgetPerUnit: 500,
        qualityPreference: 'Premium',
        requiredCertifications: ['GAP', 'ISO'],
        deliveryPreference: 'FOB',
        coldChainRequired: false,
        status: 'Active',
        firstContactDate: '2026-01-10',
    },
    {
        buyerId: 'B002',
        companyName: 'Index Supply Chain',
        contactPerson: 'David Smith',
        phone: '+447700900000',
        email: 'david@index.uk',
        country: 'UK',
        city: 'London',
        productInterest: 'Vegetables',
        quantityNeeded: 300,
        budgetPerUnit: 400,
        qualityPreference: 'Premium',
        requiredCertifications: ['GLOBALGAP'],
        deliveryPreference: 'CIF',
        coldChainRequired: true,
        maxTemperatureAcceptable: 5,
        status: 'Active',
        firstContactDate: '2026-01-11',
    },
    {
        buyerId: 'B003',
        companyName: 'Index Fresh',
        contactPerson: 'Maria Garcia',
        phone: '+34600123456',
        email: 'maria@indexfresh.es',
        country: 'Spain',
        city: 'Valencia',
        productInterest: 'Mangoes',
        quantityNeeded: 200,
        budgetPerUnit: 800,
        qualityPreference: 'Premium',
        requiredCertifications: ['GLOBALGAP'],
        deliveryPreference: 'CIF',
        coldChainRequired: true,
        status: 'Active',
        firstContactDate: '2026-01-12',
    },
    {
        buyerId: 'B004',
        companyName: 'Anture Fresh',
        contactPerson: 'Ahmed Al-Fayed',
        phone: '+971550000000',
        email: 'ahmed@anture.ae',
        country: 'UAE',
        city: 'Dubai',
        productInterest: 'Vegetables',
        quantityNeeded: 150,
        budgetPerUnit: 350,
        qualityPreference: 'Standard',
        requiredCertifications: [],
        deliveryPreference: 'CIF',
        coldChainRequired: true,
        status: 'Active',
        firstContactDate: '2026-01-12',
    },
    {
        buyerId: 'B005',
        companyName: 'Universal Cold Storage',
        contactPerson: 'Mohammed',
        phone: '+966500000000',
        email: 'mohammed@universal.sa',
        country: 'Saudi Arabia',
        city: 'Riyadh',
        productInterest: 'Tea',
        quantityNeeded: 400,
        budgetPerUnit: 450,
        qualityPreference: 'Standard',
        requiredCertifications: ['ISO'],
        deliveryPreference: 'CIF',
        coldChainRequired: false,
        status: 'Active',
        firstContactDate: '2026-01-13',
    },
    {
        buyerId: 'B006',
        companyName: 'Durowaa',
        contactPerson: 'Kwame',
        phone: '+233200000000',
        email: 'kwame@durowaa.gh',
        country: 'Ghana',
        city: 'Accra',
        productInterest: 'Mangoes',
        quantityNeeded: 100,
        budgetPerUnit: 700,
        qualityPreference: 'Standard',
        requiredCertifications: [],
        deliveryPreference: 'CIF',
        coldChainRequired: true,
        status: 'Active',
        firstContactDate: '2026-01-14',
    }
];

export const INITIAL_INTERESTS: Interest[] = [
    {
        interestId: 'I001',
        buyerId: 'B001',
        sellerId: 'S001',
        product: 'Rice',
        quantity: 500,
        dateInterested: '2026-01-14',
        status: 'Interested',
        adminNotes: 'Initial interest shown via platform',
    }
];

export const INITIAL_SHIPMENTS: Shipment[] = [
    {
        shipmentId: 'SH001',
        orderId: 'I001',
        buyerId: 'B001',
        sellerId: 'S001',
        product: 'Rice',
        quantity: 500,
        departureDate: '2026-01-20',
        expectedDeliveryDate: '2026-02-10',
        modeOfTransport: 'Sea',
        coldChainUsed: false,
        shippingStatus: 'Preparing',
        qualityMaintained: 'Yes',
        temperatureLogs: 'Ambient',
    }
];

export const INITIAL_QA: QualityAssurance[] = [];
export const INITIAL_NOTIFICATIONS: Notification[] = [];
